
services:
- postgres:alpine

variables:
  POSTGRES_USER: "redirectails"
  POSTGRESS_PASSWORD: "secretpassw0rd"
  POSTGRESS_DATABASE: "redirectails_development"
  RAILS_ENV: "test"
  DATABASE_URL: "postgres://redirectails:secretpassw0rd@postgres:5432/"

before_script:
- ruby -v                                   # Print out ruby version for debugging
- apt-get update -q && apt-get install nodejs ruby-dev -yqq
- gem install bundler --no-ri --no-rdoc     # Bundler is not installed with the image
- bundle install -j $(nproc)                # Install dependencies into usr/local/lib
- bundle update                             # Update dependencies for see new version
- rails db:setup                            # Run db:create db:migrate db:seed

stages:
- test

rspec:2.3:
  image: "ruby:2.3"
  stage: test
  script:
  - rspec spec

rspec:2.4:
  image: "ruby:2.4"
  stage: test
  script:
  - rspec spec

rspec:2.5:
  image: "ruby:2.5"
  stage: test
  script:
  - rspec spec
