# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: "ruby:2.3"

services:
- postgres:alpine

variables:
  POSTGRES_USER: "redirectails"
  POSTGRESS_PASSWORD: "secretpassw0rd"
  POSTGRESS_DATABASE: "redirectails_development"
  RAILS_ENV: "test"
  DATABASE_URL: "postgres://redirectails:secretpassw0rd@postgres:5432/"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v                                   # Print out ruby version for debugging
  - apt-get update -q && apt-get install nodejs ruby-dev -yqq
  - gem install bundler --no-ri --no-rdoc     # Bundler is not installed with the image
  - bundle update -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby

stages:
  - test

rspec:
  stage: test
  script:
  - rspec spec

rails:
  stage: test
  script:
  - rails db:setup
  - rails test
