language: ruby
rvm:
  - 2.3

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
  hosts:
    - redirectails.dev

env:
  - DATABASE_URL="postgres://postgres:@redirectails.dev:5432/"

bundler_args: --without production

before_script:
  - psql -c 'CREATE DATABASE redirectails_development;' -U postgres
  - bin/rails db:setup

script: rspec spec
