language: ruby
rvm:
- 2.4.1

services:
- postgresql

bundler_args: --without production

before_script:
- psql -c "CREATE USER redirectails WITH PASSWORD redirectails;" -U postgres
- psql -c "CREATE DATABASE redirectails_test;" -U postgres
- psql -c "GRANT ALL PRIVILEGES ON DATABASE redirectails_test TO redirectails;" -U postgres
- bin/rails db:setup

script: bundle exec rspec
