version: "3"

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: redirectails
      POSTGRES_PASSWORD: redirectails
      POSTGRES_DB: redirectails_development
    ports:
    - "5432:5432"
    networks:
    - backend

networks:
  backend:
